name: deus_mobile
description: The future of mobile trading.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.7+13

environment:
  sdk: ">=2.14.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # BACKEND
  http: ^0.13.4
  json_annotation: ^4.3.0
  equatable: ^2.0.0
  web3dart: ^2.3.1
  bip39: ^1.0.6
  hex: ^0.2.0
  pinenacl: ^0.3.3
  get_it: ^7.2.0
  flutter_bloc: ^7.3.1
  bloc: ^7.2.1
  string_validator: ^0.3.0
  flutter_secure_storage: ^4.2.1
  intl: ^0.17.0
  local_auth: ^1.1.8
  floor: ^1.2.0
  # analytics
  firebase_analytics: ^8.3.3
  firebase_core: ^1.0.1

  # FRONTEND
  pull_to_refresh: ^2.0.0
  fluttertoast: ^8.0.8
  flutter_hooks: ^0.18.0
  flutter_svg: ^0.22.0
  shimmer_animation: ^2.1.0+1
  shared_preferences: ^2.0.8
  flutter_icons: ^1.1.0
  flushbar: ^1.10.4
  page_transition: ^2.0.4
  provider: ^6.0.1
  flutter_device_type: ^0.4.0
  url_launcher: ^6.0.12
  outline_gradient_button: ^2.0.0+1
  flutter_countdown_timer: ^4.1.0
  flutter_svg_provider: ^0.1.10
  stream_transform: ^2.0.0
  fl_chart: ^0.40.2
  flutter_vibrate: ^1.3.0
  flappy_search_bar: 1.7.2
  qr_flutter: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  floor_generator: ^1.2.0
  build_runner: ^2.0.4
  built_value_generator: ^8.1.2
  json_serializable: ^6.0.0
  flutter_launcher_icons: ^0.9.0


flutter:
  uses-material-design: true
  assets:
    # FRONTEND
    - assets/images/
    - assets/images/currencies/
    - assets/images/stocks/
    - assets/images/icons/
    - assets/launcher_icon/
    - assets/icons/
    - assets/blur_screens/
    # BACKEND
    - assets/deus_data/ # data of tokens, contract ABI/functions etc.
  fonts:
    - family: Monument
      fonts:
        - asset: assets/fonts/monument-regular.ttf
          weight: 300
    - family: EduMonument
      fonts:
        - asset: assets/fonts/edumonument-regular.ttf
          weight: 300

flutter_icons: # flutter pub run flutter_launcher_icons:main
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/deus_dea.png"
