name: deus_mobile
description: The future of mobile trading.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.1.6+12

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # BACKEND
  http: ^0.13.3
  json_annotation: ^4.0.1
#  json_annotation: ^3.1.1
  equatable: ^2.0.0
  web3dart: ^2.1.4
  bip39: ^1.0.6
  hex: ^0.2.0
  tweetnacl: ^0.3.2
  get_it: ^5.0.6
  flutter_bloc: ^7.0.0
  string_validator: ^0.1.4
  flutter_secure_storage: ^4.1.0
  intl: ^0.17.0
  local_auth: ^1.1.0
  # analytics
  firebase_analytics: ^7.0.1
  firebase_core: ^1.0.1

  # FRONTEND
  fluttertoast: ^7.1.6
  flutter_hooks: ^0.9.0
  flutter_svg: ^0.22.0
  shimmer_animation: ^0.0.9+1
  shared_preferences: ^2.0.4
  flutter_icons: ^1.1.0
  flushbar: ^1.10.4
  page_transition: ^1.1.5
  provider: ^5.0.0
  flutter_device_type: ^0.2.0
  url_launcher:
  outline_gradient_button: ^1.0.0+2
  flutter_countdown_timer: ^3.0.0
  flutter_svg_provider: ^0.1.8
  stream_transform: ^2.0.0
  fl_chart: ^0.36.0
  vibration: ^1.7.2
  flappy_search_bar: 1.4.1
  floor: ^1.1.0
dependency_overrides:
#  analyzer: ^1.5.0
  convert: ^3.0.0
  fixnum: ^1.0.0
  package_config: ^2.0.0

dev_dependencies:
    # flutter_test:
    #   sdk: flutter
  floor_generator: ^1.1.0
  build_runner: ^2.0.4
  built_value_generator: ^8.1.0
  json_serializable: ^4.1.0
#  json_serializable: ^3.5.1
  flutter_launcher_icons: ^0.9.0


flutter:
  uses-material-design: true
  assets:
    # FRONTEND
    - assets/images/
    - assets/images/currencies/
    - assets/images/stocks/
    - assets/images/icons/
    - assets/launcher_icon/
    - assets/blur_screens/
    # BACKEND
    - assets/deus_data/ # data of tokens, contract ABI/functions etc.
  fonts:
    - family: Monument
      fonts:
        - asset: assets/fonts/monument-regular.ttf
          weight: 300
    - family: EduMonument
      fonts:
        - asset: assets/fonts/edumonument-regular.ttf
          weight: 300

flutter_icons: # flutter pub run flutter_launcher_icons:main
  android: "launcher_icon"
  ios: true
  image_path: "assets/launcher_icon/deus_dea.png"
